lint:
	golangci-lint run --fix

test:
	go test ./...

run:
	SENTRY_NOTIFIER_CONFIG={} SENTRY_NOTIFIER_TELEGRAM_BOT_TOKEN=aa SENTRY_NOTIFIER_TELEGRAM_CHAT_ID=1 SENTRY_NOTIFIER_TELEGRAM_CHAT_THREAD_ID=1 SENTRY_NOTIFIER_SENTRY_CLIENT_SECRET=eeee go run ./cmd/main.go
