openapi: 3.0.0
info:
  title: 'Sentry Notifier: API панели управления'
  version: '1.0.0'
  contact:
    name: Artem Ukrainskii
    email: temicska99@mail.ru

paths:
  /test:
    get:
      operationId: SendTestNotification
      parameters:
        - {$ref: '#/components/parameters/event-type-query'}
      responses:
        200: {$ref: '#/components/responses/send-test-notification-response'}

  /health:
    get:
      operationId: HealthCheck
      responses:
        200: {$ref: '#/components/responses/health-check-response'}
        500: {$ref: '#/components/responses/health-check-response'}

  /metrics:
    get:
      operationId: GetMetrics
      responses:
        default: {$ref: '#/components/responses/get-metrics-response'}

components:
  parameters:
    event-type-query:
      name: event
      in: query
      schema:
        $ref: "#/components/schemas/event-type"
      required: false

  schemas:
    event-type:
      type: string
      description: 'Тип события'
      enum: [issue, event_alert]
      default: issue

    health-check:
      type: object
      required: [status, channels]
      properties:
        status:
          type: boolean
          description: 'Статус проверки всех каналов'
          example: true
        channels:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: array
              items:
                type: object
                required: [status]
                properties:
                  status:
                    type: boolean
                    description: 'Статус проверки канала'
                    example: true
                  reason:
                    type: string
                    description: 'Описание ошибки'
                    example: 'chat_not_found'

  responses:
    get-metrics-response:
      description: Ответ на запрос метрик. В формате Prometheus.
      content:
        text/plain:
          schema:
            type: string

    health-check-response:
      description: Результат проверки здоровья
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/health-check"

    send-test-notification-response:
      description: Ответ на отправку тестовых уведомлений
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Notifications was scheduled'
